fix: do not hardcord libdir
linuxdeepin/dde-widgets pull request #47
Opened 2023-05-23 13:47 UTC by hillwoodroc

Use cmake macro instead of hardcord libdir

Log:

2023-05-24 01:37 UTC, wineee requested changes

2023-05-24 01:37 UTC, wineee commented on interface/CMakeLists.txt
> +install(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR}/${CMAKE_LIBRARY_ARCHITECTURE})
deepin/debian 上 CMAKE_INSTALL_LIBDIR 是带有 ARCHITECTURE 路径的

2023-05-24 01:37 UTC, wineee commented on interface/CMakeLists.txt
> +install(FILES ${CMAKE_CURRENT_BINARY_DIR}/DdeWidgetsConfig.cmake DESTINATION ${CMAKE_INSTALL_LIBDIR}/${CMAKE_LIBRARY_ARCHITECTURE}/cmake/DdeWidgets)
同上，应该删除 CMAKE_LIBRARY_ARCHITECTURE

2023-05-24 01:37 UTC, wineee commented on interface/CMakeLists.txt
> +set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)
dde-widgets 是硬编码读取插件路径的
https://github.com/linuxdeepin/dde-widgets/blob/bcfde634372ee3a11929a9d5e584be691e9394e2/app/widgetmanager.cpp#L418

应该继续使用 lib ，或者像控制中心一样使用宏， cc @18202781743 

https://github.com/linuxdeepin/dde-control-center/blob/ba07f6e3dbeaeb8322a17726cc57f4e855a9b111/src/frame/utils.h#L25
https://github.com/linuxdeepin/dde-control-center/blob/ba07f6e3dbeaeb8322a17726cc57f4e855a9b111/CMakeLists.txt#L78

2023-05-24 02:23 UTC, Decodetalkers commented
[  351s] -- Installing: /usr/src/packages/BUILD/debian/tmp/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/cmake/DdeWidgets/DdeWidgetsConfig.cmake

出现这种路径了，改的有问题啊

2023-05-26 03:09 UTC, wineee requested changes
另外上面已经提到插件读取路径也需要适配

2023-05-26 03:09 UTC, wineee commented on interface/CMakeLists.txt
> +install(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR}
```suggestion
install(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR})
```

2023-05-26 03:18 UTC, hillwoodroc commented on interface/CMakeLists.txt
> +set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)
改成 dirs << DefaultLibraryDirectory; 吗？

2023-05-26 03:33 UTC, 18202781743 commented
插件输出目录改了，debian/dde-widgets.intall 也需要改一下，usr/lib/dde-widgets/plugins/*改为 usr/lib/*/dde-widgets/plugins/*

2023-05-26 03:33 UTC, 18202781743 commented on interface/CMakeLists.txt
> +set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)
是的，

2023-05-26 03:36 UTC, wineee commented
> 插件输出目录改了，debian/dde-widgets.intall 也需要改一下，usr/lib/dde-widgets/plugins/_改为 usr/lib/_/dde-widgets/plugins/*

`usr/lib/*/dde-widgets/plugins/*`， 不用 ` 包裹一下 markdown 渲染会出错

2023-05-26 03:40 UTC, wineee commented on interface/CMakeLists.txt
> +set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)
我觉得 DefaultPluginDirectory 更好，另外 dde-control-center 修改时兼容了旧插件地址，因为有些三方库也提供 dde-control-center 的插件

dde-widgets 是新项目，如果没有三方插件就不需要兼容旧路径， @18202781743 目前应该没有其他项目提供 dde-widgets 的插件吧？

2023-05-26 04:07 UTC, 18202781743 commented on interface/CMakeLists.txt
> +set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)
是不需要兼容，

2023-05-26 05:11 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
你好歹看下路径啊

add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")

2023-05-26 05:12 UTC, 18202781743 commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
这个值是  lib/x86_64-linux-gnu ？插件无法加载，
可以打包测试一下， `QT_LOGGING_RULES="dde*.debug=true" dde-widgets -s`
![image](https://github.com/linuxdeepin/dde-widgets/assets/20967670/7d3ebc95-41b9-4318-b96a-2c9aadf0db91)

2023-05-26 05:13 UTC, Decodetalkers commented on app/widgetmanager.cpp
> +    dirs << DefaultPluginyDirectory;
不应该直接使用宏，应该把宏转换成QString

```
const QString PLUGIN_DIRECTORY = QStringLiteral(DefaultPluginyDirectory);
```

在这个文件最上面定义一个变量，然后使用这个变量

2023-05-26 05:13 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
是，要用full的

2023-05-26 05:26 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
上面定义了 `set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)`，用这个变量，把 CMAKE_INSTALL_LIBDIR 改成 CMAKE_INSTALL_FULL_LIBDIR

2023-05-26 07:58 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
你们那边不会自动传递 /usr 路径？

2023-05-26 08:30 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
https://gitlab.kitware.com/cmake/cmake/-/issues/20250
CMAKE_INSTALL_LIBDIR 应该是包含了 /usr 的

2023-05-26 08:37 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
> https://gitlab.kitware.com/cmake/cmake/-/issues/20250 CMAKE_INSTALL_LIBDIR 应该是包含了 /usr 的

cmake_install_libdir 不包含prefix的，你要使用full的

2023-05-26 08:47 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
https://gitlab.kitware.com/cmake/cmake/-/issues/20250
CMAKE_INSTALL_LIBDIR 应该是包含了 /usr 的

2023-05-26 08:54 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
CMAKE_INSTALL_LIBDIR 不包含 /usr ，它一般是相对路径，cmake 安装时会自动和 CMAKE_INSTALL_PREFIX 拼接

2023-05-27 08:27 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
dtkcore 就是包含了 /usr 的 https://github.com/linuxdeepin/dtkcore/blob/50ff1e70fb1d46c1a995a007679b0ec579333a77/CMakeLists.txt#L25

2023-05-27 08:28 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
你再看看 dtkcore 的 CMakeList.txt https://github.com/linuxdeepin/dtkcore/blob/50ff1e70fb1d46c1a995a007679b0ec579333a77/CMakeLists.txt#L25

2023-05-27 08:33 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
最前面加一行 include(GNUInstallDirs) 就行了。

2023-05-27 08:45 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
> 上面定义了 `set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)`，用这个变量，把 CMAKE_INSTALL_LIBDIR 改成 CMAKE_INSTALL_FULL_LIBDIR

PLUGIN_INSTALL_DIR 是子文件定义的变量，恐怕传递不到主文件里吧。

2023-05-27 10:40 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
没有Include是不存在这个变量的，就是include了这个变量才会生效，没有full的那个变量是没有prefix的，你可以打印下这个变量啊

2023-05-27 10:43 UTC, Decodetalkers commented on CMakeLists.txt
> +include(GNUInstallDirs)
include要在15行后

2023-05-27 10:43 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")
你打印下这个值把，它应该是没有o你先自己打印下这个值看看对不对吧

2023-05-27 12:13 UTC, hillwoodroc commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")
我这儿的确是有的，如果我强行在前面加上 ${CMAKE_INSTALL_PREFIX}，那我这儿整个路径就成了 /usr/usr/dde-widgets/plugins

2023-05-27 13:15 UTC, hillwoodroc commented on app/widgetmanager.cpp
> +    dirs << DefaultPluginyDirectory;
不知道为什么会报错。
![图片](https://github.com/linuxdeepin/dde-widgets/assets/1880237/92111ca6-c412-455f-b026-00686014828b)

2023-05-27 13:46 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
> > 上面定义了 `set(PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins)`，用这个变量，把 CMAKE_INSTALL_LIBDIR 改成 CMAKE_INSTALL_FULL_LIBDIR
> 
> PLUGIN_INSTALL_DIR 是子文件定义的变量，恐怕传递不到主文件里吧。

那就把 PLUGIN_INSTALL_DIR 定义放到上层 cmakelist.txt

2023-05-27 13:47 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")
CMAKE_INSTALL_FULL_LIBDIR

我知道Fedora会去传，但是这个没有Full的不应该是绝对路径，你不要用打包环境测试

2023-05-27 13:48 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}")
> dtkcore 就是包含了 /usr 的 [linuxdeepin/dtkcore@`50ff1e7`/CMakeLists.txt#L25](https://github.com/linuxdeepin/dtkcore/blob/50ff1e70fb1d46c1a995a007679b0ec579333a77/CMakeLists.txt#L25)

对 cmake 管理的路径而言是对的，因为 cmake 在安装时会处理相对路径，但是我们要把值传给 c++，必须保证 PLUGIN_INSTALL_DIR 是绝对路径才行

2023-05-27 13:48 UTC, Decodetalkers commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")
> 我这儿的确是有的，如果我强行在前面加上 ${CMAKE_INSTALL_PREFIX}，那我这儿整个路径就成了 /usr/usr/lib64/dde-widgets/plugins

不是说叫你加Prefix，cmake这些变量还有个Full版本的，让你用那个

2023-05-27 13:51 UTC, Decodetalkers commented on app/widgetmanager.cpp
> +const QString PLUGIN_DIRECTORY = QStringLiteral(DefaultPluginyDirectory);
写错了啊，你没有你这是Typo，你没有用Lsp吗？

2023-05-27 13:51 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DDefaultPluginyDirectory="${CMAKE_INSTALL_LIBDIR}/dde-widgets/plugins")
CMAKE_INSTALL_LIBDIR 默认是相对路径，但是有的构建系统会给他传绝对路径，所以推荐用 CMAKE_INSTALL_FULL_LIBDIR，而不是自己拼接 CMAKE_INSTALL_PREFIX

2023-05-27 13:56 UTC, hillwoodroc commented on app/widgetmanager.cpp
> +const QString PLUGIN_DIRECTORY = QStringLiteral(DefaultPluginyDirectory);
我不懂 C++，不知道怎么处理。

2023-05-27 13:57 UTC, Decodetalkers commented on app/widgetmanager.cpp
> +const QString PLUGIN_DIRECTORY = QStringLiteral(DefaultPluginyDirectory);
你宏写错了。。

2023-05-27 14:01 UTC, Decodetalkers commented on interface/CMakeLists.txt
>  file(GLOB INTERFACES
最上面include一次就可以了，不需要include两次

2023-05-28 12:21 UTC, Decodetalkers commented on interface/DdeWidgetsConfig.cmake
> +    install(TARGETS ${plugin} DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}/dde-widgets/plugins)
install的时候就没必要Full啦

2023-05-28 12:30 UTC, Decodetalkers commented on interface/CMakeLists.txt
> +    INSTALL_DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}/cmake/DdeWidgets
这里没必要修改

2023-05-28 12:30 UTC, Decodetalkers commented on worldclock/CMakeLists.txt
> +install(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}/dde-widgets/plugins)
这里不需要Full

2023-05-28 12:32 UTC, Decodetalkers commented on interface/CMakeLists.txt
> +    INSTALL_DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}/cmake/DdeWidgets
还有这里啊

2023-05-28 14:07 UTC, Decodetalkers reviewed
+1

2023-05-29 05:11 UTC, 18202781743 approved these changes

2023-05-29 05:14 UTC, 18202781743 commented
/merge

2023-05-29 05:14 UTC, merged